version: "3.8"

services:
  db:
    build: ./db  # ✅ Now using custom Dockerfile in db directory
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chessuser -d chessapp"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./rest-api
    container_name: chess_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://chessuser:chesspassword@db:5432/chessapp
      NODE_ENV: production
    env_file:
      - .env
    expose:
      - "5000"

  next:
    build: ./next-server
    container_name: frontend
    restart: always
    environment:
      NODE_ENV: production
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    depends_on:
      - api
      - next
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pgdata:
