services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: chessuser
      POSTGRES_PASSWORD: chesspassword
      POSTGRES_DB: chessapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  api:
    build: ./rest-api
    container_name: chess_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://chessuser:chesspassword@db:5432/chessapp
      NODE_ENV: production
    expose:
      - "5000"

  next:
    build: ./next-server
    container_name: frontend
    restart: always
    environment:
      NODE_ENV: production
    expose:
      - "3000"

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    depends_on:
      - api
      - next
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pgdata:
